apiVersion: apps/v1
kind: Deployment
metadata:
  name: concesionario-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: concesionario
  template:
    metadata:
      labels:
        app: concesionario
    spec:
      containers:
      - name: concesionario
        image: concesionarioarc.azurecr.io/concesionario-app:latest
        imagePullPolicy: Always
        command: ["sleep", "infinity"]
